name: Release

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose

  build:
    needs: test
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - os: macos-15
            filename: "file-checker"
            outfilename: "file-checker-mac"
          - os: windows-2022
            filename: "file-checker.exe"
            outfilename: "file-checker-win.exe"
          - os: ubuntu-latest
            filename: "file-checker"
            outfilename: "file-checker-linux"

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Rename artifact
      run: |
        mv ./build/release/${{ matrix.filename }} ./build/release/${{ matrix.outfilename }} 

    - name: Store build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: ./build/release/${{ matrix.outfilename }}
  
  release:
    needs: [test, build]
    runs-on: ubuntu-latest
    environment:
      name: ReleaseBot
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}